spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret

spring.docker.compose.enabled=true
spring.docker.compose.file=Atlaz-BackEnd/AtlazDB/docker-compose.yml

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
