spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.bzednaygfhvrbmxioqbu
spring.datasource.password=${DB_PASSWORD}

spring.docker.compose.enabled=false

spring.jpa.show-sql=false